name: Deploy

on:
  push:
    branches: [main]

jobs:

  Website:
    runs-on: ubuntu-latest
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
    - uses: actions/checkout@v2
    # Install node version 12
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    # Install npm packages
    - name: Install frontend dependencies
      run: cd frontend && npm install

    # Build react app
    - name: Build the frontend
      run: cd frontend && CI=false npm run build

    # Install Surge
    - name: Install Surge
      run: npm install -g surge

    # Deploy to the defined URL using the token
    - name: Deploy to surge
      run: surge ./build http://www.cicd-web3.surge.sh --token ${{secrets.SURGE_TOKEN}}
